[package]
name = "tunnel"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
url = { workspace = true }
